steps:
  # Step 1: Build Docker image and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-and-push'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:latest'
      - '-f'
      - 'infrastructure/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:latest'

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'kabro-netzero-api'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:${COMMIT_SHA}'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=120'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--allow-unauthenticated'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=config.settings,DEBUG=False,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-secrets=SECRET_KEY=kabro-netzero-secret-key:latest,MONGODB_URI=kabro-netzero-mongodb-uri:latest,JWT_SECRET=kabro-netzero-jwt-secret:latest'

# Images to push to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/kabro-netzero/kabro-netzero-api:latest'

# Timeout for entire build
timeout: '3600s'

# Substitutions for dynamic variables
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'kabro-netzero-api'
  _MEMORY: '1Gi'
  _CPU: '1'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
